/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.visitor;

import org.postgresql.stado.parser.core.syntaxtree.*;

public interface IRetVisitor<R> {

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeToken n);

  public R visit(final numberValue n);

  public R visit(final stringLiteral n);

  public R visit(final UnreservedWords n);

  public R visit(final Identifier n);

  public R visit(final process n);

  public R visit(final CopyData n);

  public R visit(final FormatDefOIDS n);

  public R visit(final FormatDefDelimiter n);

  public R visit(final FormatDefNull n);

  public R visit(final FormatDefCSV n);

  public R visit(final AddNodeToDB n);

  public R visit(final DropNodeFromDB n);

  public R visit(final StartDatabase n);

  public R visit(final StopDatabase n);

  public R visit(final ShutdownXDB n);

  public R visit(final CreateDatabase n);

  public R visit(final DropDatabase n);

  public R visit(final CreateNode n);

  public R visit(final FormatDefPort n);

  public R visit(final FormatDefUser n);

  public R visit(final FormatDefPassword n);

  public R visit(final ExecDirect n);

  public R visit(final Explain n);

  public R visit(final VacuumDatabase n);

  public R visit(final AnalyzeDatabase n);

  public R visit(final CreateTablespace n);

  public R visit(final DropTablespace n);

  public R visit(final TablespaceLocation n);

  public R visit(final UpdateStats n);

  public R visit(final RenameTable n);

  public R visit(final DropIndex n);

  public R visit(final Alter n);

  public R visit(final AlterTableSpace n);

  public R visit(final AlterTable n);

  public R visit(final AlterTableActon n);

  public R visit(final Inherit n);

  public R visit(final SetTablespace n);

  public R visit(final SetProperty n);

  public R visit(final IsolationLevel n);

  public R visit(final ShowProperty n);

  public R visit(final OwnerDef n);

  public R visit(final Constraint n);

  public R visit(final AddDef n);

  public R visit(final DropDef n);

  public R visit(final RenameDef n);

  public R visit(final AlterDef n);

  public R visit(final AlterDefOperation n);

  public R visit(final AlterDefOperationType n);

  public R visit(final AlterDefOperationSet n);

  public R visit(final DropDefaultNotNull n);

  public R visit(final Delete n);

  public R visit(final UpdateTable n);

  public R visit(final SetUpdateClause n);

  public R visit(final createIndex n);

  public R visit(final columnListIndexSpec n);

  public R visit(final createTable n);

  public R visit(final OnCommitClause n);

  public R visit(final WithXRowID n);

  public R visit(final tablespaceDef n);

  public R visit(final inheritsDef n);

  public R visit(final createView n);

  public R visit(final ColumnNameListWithParenthesis n);

  public R visit(final DropView n);

  public R visit(final dropTable n);

  public R visit(final InsertTable n);

  public R visit(final PrimaryKeyDef n);

  public R visit(final CheckDef n);

  public R visit(final CreateDefinition n);

  public R visit(final ColumnDeclare n);

  public R visit(final ForeignKeyDef n);

  public R visit(final DefaultSpec n);

  public R visit(final PartitionDeclare n);

  public R visit(final PartitionChoice n);

  public R visit(final NodePartitionList n);

  public R visit(final types n);

  public R visit(final DatetimeField n);

  public R visit(final IntervalQualifier n);

  public R visit(final IntervalDataType n);

  public R visit(final TextDataType n);

  public R visit(final BLOBDataType n);

  public R visit(final BitDataType n);

  public R visit(final VarBitDataType n);

  public R visit(final MacAddrDataType n);

  public R visit(final CidrDataType n);

  public R visit(final InetDataType n);

  public R visit(final GeometryDataType n);

  public R visit(final Box2DDataType n);

  public R visit(final Box3DDataType n);

  public R visit(final Box3DExtentDataType n);

  public R visit(final RegClassDataType n);

  public R visit(final BooleanDataType n);

  public R visit(final SmallIntDataType n);

  public R visit(final BigIntDataType n);

  public R visit(final SerialDataType n);

  public R visit(final BigSerialDataType n);

  public R visit(final RealDataType n);

  public R visit(final IntegerDataType n);

  public R visit(final FloatDataType n);

  public R visit(final TimeStampDataType n);

  public R visit(final TimeDataType n);

  public R visit(final DateDataType n);

  public R visit(final VarCharDataType n);

  public R visit(final NumericDataType n);

  public R visit(final DecimalDataType n);

  public R visit(final FixedDataType n);

  public R visit(final NationalCharDataType n);

  public R visit(final DoublePrecision n);

  public R visit(final CharachterDataType n);

  public R visit(final LengthSpec n);

  public R visit(final UnsignedZeroFillSpecs n);

  public R visit(final PrecisionSpec n);

  public R visit(final SelectAddGeometryColumn n);

  public R visit(final SelectWithParenthesis n);

  public R visit(final Select n);

  public R visit(final SelectWithoutOrderWithParenthesis n);

  public R visit(final SelectWithoutOrder n);

  public R visit(final SelectWithoutOrderAndSetWithParenthesis n);

  public R visit(final UnionSpec n);

  public R visit(final WithList n);

  public R visit(final WithDef n);

  public R visit(final WithSelect n);

  public R visit(final SelectWithoutOrderAndSet n);

  public R visit(final SelectList n);

  public R visit(final SelectTupleSpec n);

  public R visit(final SQLSimpleExpression n);

  public R visit(final SQLPrecedenceLevel1Expression n);

  public R visit(final SQLPrecedenceLevel1Operand n);

  public R visit(final SQLPrecedenceLevel2Expression n);

  public R visit(final SQLPrecedenceLevel2Operand n);

  public R visit(final SQLPrecedenceLevel3Expression n);

  public R visit(final SQLPrecedenceLevel3Operand n);

  public R visit(final SQLPrimaryExpression n);

  public R visit(final IsNullExpression n);

  public R visit(final IsBooleanExpression n);

  public R visit(final PreparedStmtParameter n);

  public R visit(final TimeStampLiteral n);

  public R visit(final TimeLiteral n);

  public R visit(final DateLiteral n);

  public R visit(final IntervalLiterals n);

  public R visit(final TextLiterals n);

  public R visit(final NullLiterals n);

  public R visit(final booleanLiteral n);

  public R visit(final binaryLiteral n);

  public R visit(final hex_decimalLiteral n);

  public R visit(final IntegerLiteral n);

  public R visit(final MacaddrLiteral n);

  public R visit(final CidrLiteral n);

  public R visit(final InetLiteral n);

  public R visit(final GeometryLiteral n);

  public R visit(final PseudoColumn n);

  public R visit(final SQLArgumentList n);

  public R visit(final SQLArgument n);

  public R visit(final CharString n);

  public R visit(final FunctionCall n);

  public R visit(final Func_Custom n);

  public R visit(final Func_NullIf n);

  public R visit(final Func_Coalesce n);

  public R visit(final Func_ClockTimeStamp n);

  public R visit(final Func_StatementTimeStamp n);

  public R visit(final Func_TransactionTimeStamp n);

  public R visit(final Func_CurrentDatabase n);

  public R visit(final Func_CurrentSchema n);

  public R visit(final Func_Version n);

  public R visit(final Func_BitAnd n);

  public R visit(final Func_BitOr n);

  public R visit(final Func_BoolAnd n);

  public R visit(final Func_BoolOr n);

  public R visit(final Func_CorrCov n);

  public R visit(final Func_Regr n);

  public R visit(final Func_Substring n);

  public R visit(final Func_Position n);

  public R visit(final Func_Overlay n);

  public R visit(final Func_Convert n);

  public R visit(final Func_Extract n);

  public R visit(final Func_User n);

  public R visit(final Func_Case n);

  public R visit(final Func_Trim n);

  public R visit(final Func_Avg n);

  public R visit(final Func_Count n);

  public R visit(final Func_Max n);

  public R visit(final Func_Min n);

  public R visit(final Func_Stdev n);

  public R visit(final Func_Variance n);

  public R visit(final Func_Sum n);

  public R visit(final length n);

  public R visit(final position n);

  public R visit(final TableColumn n);

  public R visit(final extendbObject n);

  public R visit(final SelectAliasSpec n);

  public R visit(final AliasName n);

  public R visit(final SQLComplexExpression n);

  public R visit(final SQLAndExpression n);

  public R visit(final SQLORExpression n);

  public R visit(final SQLAndExp n);

  public R visit(final SQLUnaryLogicalExpression n);

  public R visit(final SQLCondResult n);

  public R visit(final ExistsClause n);

  public R visit(final SQLRelationalExpression n);

  public R visit(final SQLRelationalOperatorExpression n);

  public R visit(final Relop n);

  public R visit(final SQLInClause n);

  public R visit(final SQLBetweenClause n);

  public R visit(final SQLLikeClause n);

  public R visit(final SubQuery n);

  public R visit(final IsNullClause n);

  public R visit(final IsBooleanClause n);

  public R visit(final IntoClause n);

  public R visit(final FromClause n);

  public R visit(final TableSpec n);

  public R visit(final TableList n);

  public R visit(final FromTableSpec n);

  public R visit(final JoinSpec n);

  public R visit(final WhereClause n);

  public R visit(final GroupByClause n);

  public R visit(final SQLExpressionList n);

  public R visit(final SQLExpressionListItem n);

  public R visit(final HavingClause n);

  public R visit(final OrderByClause n);

  public R visit(final LimitClause n);

  public R visit(final OffsetClause n);

  public R visit(final OrderByItem n);

  public R visit(final Func_PgCurrentDate n);

  public R visit(final Func_PgCurrentTime n);

  public R visit(final Func_PgCurrentTimeStamp n);

  public R visit(final Func_Cast n);

  public R visit(final ColumnNameList n);

  public R visit(final TableName n);

  public R visit(final FloatingPointNumber n);

  public R visit(final ShowAgents n);

  public R visit(final ShowCluster n);

  public R visit(final ShowDatabases n);

  public R visit(final ShowStatements n);

  public R visit(final ShowTables n);

  public R visit(final ShowTranIsolation n);

  public R visit(final BeginTransaction n);

  public R visit(final CommitTransaction n);

  public R visit(final RollbackTransaction n);

  public R visit(final DescribeTable n);

  public R visit(final ShowConstraints n);

  public R visit(final ShowIndexes n);

  public R visit(final ShowUsers n);

  public R visit(final ShowViews n);

  public R visit(final Deallocate n);

  public R visit(final CreateUser n);

  public R visit(final DropUser n);

  public R visit(final AlterUser n);

  public R visit(final Grantee n);

  public R visit(final GranteeList n);

  public R visit(final TableListForGrant n);

  public R visit(final Privilege n);

  public R visit(final PrivilegeList n);

  public R visit(final Grant n);

  public R visit(final Revoke n);

  public R visit(final Cluster n);

  public R visit(final Truncate n);

  public R visit(final Kill n);

  public R visit(final Unlisten n);

  public R visit(final DeclareCursor n);

  public R visit(final CloseCursor n);

  public R visit(final FetchCursor n);

  public R visit(final AlterCluster n);

}
