/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.visitor;

import org.postgresql.stado.parser.core.syntaxtree.*;

public interface IVoidVisitor {

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeToken n);

  public void visit(final numberValue n);

  public void visit(final stringLiteral n);

  public void visit(final UnreservedWords n);

  public void visit(final Identifier n);

  public void visit(final process n);

  public void visit(final CopyData n);

  public void visit(final FormatDefOIDS n);

  public void visit(final FormatDefDelimiter n);

  public void visit(final FormatDefNull n);

  public void visit(final FormatDefCSV n);

  public void visit(final AddNodeToDB n);

  public void visit(final DropNodeFromDB n);

  public void visit(final StartDatabase n);

  public void visit(final StopDatabase n);

  public void visit(final ShutdownXDB n);

  public void visit(final CreateDatabase n);

  public void visit(final DropDatabase n);

  public void visit(final CreateNode n);

  public void visit(final FormatDefPort n);

  public void visit(final FormatDefUser n);

  public void visit(final FormatDefPassword n);

  public void visit(final ExecDirect n);

  public void visit(final Explain n);

  public void visit(final VacuumDatabase n);

  public void visit(final AnalyzeDatabase n);

  public void visit(final CreateTablespace n);

  public void visit(final DropTablespace n);

  public void visit(final TablespaceLocation n);

  public void visit(final UpdateStats n);

  public void visit(final RenameTable n);

  public void visit(final DropIndex n);

  public void visit(final Alter n);

  public void visit(final AlterTableSpace n);

  public void visit(final AlterTable n);

  public void visit(final AlterTableActon n);

  public void visit(final Inherit n);

  public void visit(final SetTablespace n);

  public void visit(final SetProperty n);

  public void visit(final IsolationLevel n);

  public void visit(final ShowProperty n);

  public void visit(final OwnerDef n);

  public void visit(final Constraint n);

  public void visit(final AddDef n);

  public void visit(final DropDef n);

  public void visit(final RenameDef n);

  public void visit(final AlterDef n);

  public void visit(final AlterDefOperation n);

  public void visit(final AlterDefOperationType n);

  public void visit(final AlterDefOperationSet n);

  public void visit(final DropDefaultNotNull n);

  public void visit(final Delete n);

  public void visit(final UpdateTable n);

  public void visit(final SetUpdateClause n);

  public void visit(final createIndex n);

  public void visit(final columnListIndexSpec n);

  public void visit(final createTable n);

  public void visit(final OnCommitClause n);

  public void visit(final WithXRowID n);

  public void visit(final tablespaceDef n);

  public void visit(final inheritsDef n);

  public void visit(final createView n);

  public void visit(final ColumnNameListWithParenthesis n);

  public void visit(final DropView n);

  public void visit(final dropTable n);

  public void visit(final InsertTable n);

  public void visit(final PrimaryKeyDef n);

  public void visit(final CheckDef n);

  public void visit(final CreateDefinition n);

  public void visit(final ColumnDeclare n);

  public void visit(final ForeignKeyDef n);

  public void visit(final DefaultSpec n);

  public void visit(final PartitionDeclare n);

  public void visit(final PartitionChoice n);

  public void visit(final NodePartitionList n);

  public void visit(final types n);

  public void visit(final DatetimeField n);

  public void visit(final IntervalQualifier n);

  public void visit(final IntervalDataType n);

  public void visit(final TextDataType n);

  public void visit(final BLOBDataType n);

  public void visit(final BitDataType n);

  public void visit(final VarBitDataType n);

  public void visit(final MacAddrDataType n);

  public void visit(final CidrDataType n);

  public void visit(final InetDataType n);

  public void visit(final GeometryDataType n);

  public void visit(final Box2DDataType n);

  public void visit(final Box3DDataType n);

  public void visit(final Box3DExtentDataType n);

  public void visit(final RegClassDataType n);

  public void visit(final BooleanDataType n);

  public void visit(final SmallIntDataType n);

  public void visit(final BigIntDataType n);

  public void visit(final SerialDataType n);

  public void visit(final BigSerialDataType n);

  public void visit(final RealDataType n);

  public void visit(final IntegerDataType n);

  public void visit(final FloatDataType n);

  public void visit(final TimeStampDataType n);

  public void visit(final TimeDataType n);

  public void visit(final DateDataType n);

  public void visit(final VarCharDataType n);

  public void visit(final NumericDataType n);

  public void visit(final DecimalDataType n);

  public void visit(final FixedDataType n);

  public void visit(final NationalCharDataType n);

  public void visit(final DoublePrecision n);

  public void visit(final CharachterDataType n);

  public void visit(final LengthSpec n);

  public void visit(final UnsignedZeroFillSpecs n);

  public void visit(final PrecisionSpec n);

  public void visit(final SelectAddGeometryColumn n);

  public void visit(final SelectWithParenthesis n);

  public void visit(final Select n);

  public void visit(final SelectWithoutOrderWithParenthesis n);

  public void visit(final SelectWithoutOrder n);

  public void visit(final SelectWithoutOrderAndSetWithParenthesis n);

  public void visit(final UnionSpec n);

  public void visit(final WithList n);

  public void visit(final WithDef n);

  public void visit(final WithSelect n);

  public void visit(final SelectWithoutOrderAndSet n);

  public void visit(final SelectList n);

  public void visit(final SelectTupleSpec n);

  public void visit(final SQLSimpleExpression n);

  public void visit(final SQLPrecedenceLevel1Expression n);

  public void visit(final SQLPrecedenceLevel1Operand n);

  public void visit(final SQLPrecedenceLevel2Expression n);

  public void visit(final SQLPrecedenceLevel2Operand n);

  public void visit(final SQLPrecedenceLevel3Expression n);

  public void visit(final SQLPrecedenceLevel3Operand n);

  public void visit(final SQLPrimaryExpression n);

  public void visit(final IsNullExpression n);

  public void visit(final IsBooleanExpression n);

  public void visit(final PreparedStmtParameter n);

  public void visit(final TimeStampLiteral n);

  public void visit(final TimeLiteral n);

  public void visit(final DateLiteral n);

  public void visit(final IntervalLiterals n);

  public void visit(final TextLiterals n);

  public void visit(final NullLiterals n);

  public void visit(final booleanLiteral n);

  public void visit(final binaryLiteral n);

  public void visit(final hex_decimalLiteral n);

  public void visit(final IntegerLiteral n);

  public void visit(final MacaddrLiteral n);

  public void visit(final CidrLiteral n);

  public void visit(final InetLiteral n);

  public void visit(final GeometryLiteral n);

  public void visit(final PseudoColumn n);

  public void visit(final SQLArgumentList n);

  public void visit(final SQLArgument n);

  public void visit(final CharString n);

  public void visit(final FunctionCall n);

  public void visit(final Func_Custom n);

  public void visit(final Func_NullIf n);

  public void visit(final Func_Coalesce n);

  public void visit(final Func_ClockTimeStamp n);

  public void visit(final Func_StatementTimeStamp n);

  public void visit(final Func_TransactionTimeStamp n);

  public void visit(final Func_CurrentDatabase n);

  public void visit(final Func_CurrentSchema n);

  public void visit(final Func_Version n);

  public void visit(final Func_BitAnd n);

  public void visit(final Func_BitOr n);

  public void visit(final Func_BoolAnd n);

  public void visit(final Func_BoolOr n);

  public void visit(final Func_CorrCov n);

  public void visit(final Func_Regr n);

  public void visit(final Func_Substring n);

  public void visit(final Func_Position n);

  public void visit(final Func_Overlay n);

  public void visit(final Func_Convert n);

  public void visit(final Func_Extract n);

  public void visit(final Func_User n);

  public void visit(final Func_Case n);

  public void visit(final Func_Trim n);

  public void visit(final Func_Avg n);

  public void visit(final Func_Count n);

  public void visit(final Func_Max n);

  public void visit(final Func_Min n);

  public void visit(final Func_Stdev n);

  public void visit(final Func_Variance n);

  public void visit(final Func_Sum n);

  public void visit(final length n);

  public void visit(final position n);

  public void visit(final TableColumn n);

  public void visit(final extendbObject n);

  public void visit(final SelectAliasSpec n);

  public void visit(final AliasName n);

  public void visit(final SQLComplexExpression n);

  public void visit(final SQLAndExpression n);

  public void visit(final SQLORExpression n);

  public void visit(final SQLAndExp n);

  public void visit(final SQLUnaryLogicalExpression n);

  public void visit(final SQLCondResult n);

  public void visit(final ExistsClause n);

  public void visit(final SQLRelationalExpression n);

  public void visit(final SQLRelationalOperatorExpression n);

  public void visit(final Relop n);

  public void visit(final SQLInClause n);

  public void visit(final SQLBetweenClause n);

  public void visit(final SQLLikeClause n);

  public void visit(final SubQuery n);

  public void visit(final IsNullClause n);

  public void visit(final IsBooleanClause n);

  public void visit(final IntoClause n);

  public void visit(final FromClause n);

  public void visit(final TableSpec n);

  public void visit(final TableList n);

  public void visit(final FromTableSpec n);

  public void visit(final JoinSpec n);

  public void visit(final WhereClause n);

  public void visit(final GroupByClause n);

  public void visit(final SQLExpressionList n);

  public void visit(final SQLExpressionListItem n);

  public void visit(final HavingClause n);

  public void visit(final OrderByClause n);

  public void visit(final LimitClause n);

  public void visit(final OffsetClause n);

  public void visit(final OrderByItem n);

  public void visit(final Func_PgCurrentDate n);

  public void visit(final Func_PgCurrentTime n);

  public void visit(final Func_PgCurrentTimeStamp n);

  public void visit(final Func_Cast n);

  public void visit(final ColumnNameList n);

  public void visit(final TableName n);

  public void visit(final FloatingPointNumber n);

  public void visit(final ShowAgents n);

  public void visit(final ShowCluster n);

  public void visit(final ShowDatabases n);

  public void visit(final ShowStatements n);

  public void visit(final ShowTables n);

  public void visit(final ShowTranIsolation n);

  public void visit(final BeginTransaction n);

  public void visit(final CommitTransaction n);

  public void visit(final RollbackTransaction n);

  public void visit(final DescribeTable n);

  public void visit(final ShowConstraints n);

  public void visit(final ShowIndexes n);

  public void visit(final ShowUsers n);

  public void visit(final ShowViews n);

  public void visit(final Deallocate n);

  public void visit(final CreateUser n);

  public void visit(final DropUser n);

  public void visit(final AlterUser n);

  public void visit(final Grantee n);

  public void visit(final GranteeList n);

  public void visit(final TableListForGrant n);

  public void visit(final Privilege n);

  public void visit(final PrivilegeList n);

  public void visit(final Grant n);

  public void visit(final Revoke n);

  public void visit(final Cluster n);

  public void visit(final Truncate n);

  public void visit(final Kill n);

  public void visit(final Unlisten n);

  public void visit(final DeclareCursor n);

  public void visit(final CloseCursor n);

  public void visit(final FetchCursor n);

  public void visit(final AlterCluster n);

}
