/* Generated By:JavaCC: Do not edit this line. CSQLParserConstants.java */
package org.postgresql.stado.parser.core;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CSQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT_LINE = 5;
  /** RegularExpression Id. */
  int COMMENT_BLOCK = 6;
  /** RegularExpression Id. */
  int NOT_BITWISE_ = 7;
  /** RegularExpression Id. */
  int LESS_ = 8;
  /** RegularExpression Id. */
  int EQUALS_ = 9;
  /** RegularExpression Id. */
  int GREATER_ = 10;
  /** RegularExpression Id. */
  int OR_BITWISE_ = 11;
  /** RegularExpression Id. */
  int MINUS_ = 12;
  /** RegularExpression Id. */
  int SEMICOLON_ = 13;
  /** RegularExpression Id. */
  int FACTORIAL_ = 14;
  /** RegularExpression Id. */
  int DIVIDE_ = 15;
  /** RegularExpression Id. */
  int QUOTE = 16;
  /** RegularExpression Id. */
  int PARENTHESIS_START_ = 17;
  /** RegularExpression Id. */
  int PARENTHESIS_CLOSE_ = 18;
  /** RegularExpression Id. */
  int ABSOLUTE_ = 19;
  /** RegularExpression Id. */
  int STAR_ = 20;
  /** RegularExpression Id. */
  int AND_BITWISE_ = 21;
  /** RegularExpression Id. */
  int XOR_BITWISE_ = 22;
  /** RegularExpression Id. */
  int MODULO_ = 23;
  /** RegularExpression Id. */
  int PLUS_ = 24;
  /** RegularExpression Id. */
  int GIS_SAME_ = 25;
  /** RegularExpression Id. */
  int REGEX_MATCHES_CASE_INSTV_ = 26;
  /** RegularExpression Id. */
  int SHIFT_LEFT_BITWISE_ = 27;
  /** RegularExpression Id. */
  int LESS_EQUALS_ = 28;
  /** RegularExpression Id. */
  int NOT_EQUALS_2_ = 29;
  /** RegularExpression Id. */
  int GREATER_EQUALS_ = 30;
  /** RegularExpression Id. */
  int SHIFT_RIGHT_BITWISE_ = 31;
  /** RegularExpression Id. */
  int CONCAT_ = 32;
  /** RegularExpression Id. */
  int SQUARE_ROOT_ = 33;
  /** RegularExpression Id. */
  int REGEX_NOT_MATCHES_ = 34;
  /** RegularExpression Id. */
  int NOT_EQUALS_ = 35;
  /** RegularExpression Id. */
  int FACTORIAL_PREFIX_ = 36;
  /** RegularExpression Id. */
  int GIS_OVERLAPS_LEFT_ = 37;
  /** RegularExpression Id. */
  int GIS_OVERLAPS_RIGHT_ = 38;
  /** RegularExpression Id. */
  int GIS_OVERLAPS_ = 39;
  /** RegularExpression Id. */
  int AS_ = 40;
  /** RegularExpression Id. */
  int IN_ = 41;
  /** RegularExpression Id. */
  int IS_ = 42;
  /** RegularExpression Id. */
  int NO_ = 43;
  /** RegularExpression Id. */
  int ON_ = 44;
  /** RegularExpression Id. */
  int OR_ = 45;
  /** RegularExpression Id. */
  int TO_ = 46;
  /** RegularExpression Id. */
  int CONTAINED_WITHIN_OR_EQUALS_ = 47;
  /** RegularExpression Id. */
  int GIS_STRICT_BELOW_ = 48;
  /** RegularExpression Id. */
  int CONTAINS_OR_EQUALS_ = 49;
  /** RegularExpression Id. */
  int GIS_STRICT_ABOVE_ = 50;
  /** RegularExpression Id. */
  int CUBE_ROOT_ = 51;
  /** RegularExpression Id. */
  int GIS_OVERLAPS_ABOVE_ = 52;
  /** RegularExpression Id. */
  int REGEX_NOT_MATCHES_CASE_INSTV_ = 53;
  /** RegularExpression Id. */
  int LEFTOUTER_ = 54;
  /** RegularExpression Id. */
  int GIS_OVERLAPS_BELOW_ = 55;
  /** RegularExpression Id. */
  int ADD_ = 56;
  /** RegularExpression Id. */
  int ALL_ = 57;
  /** RegularExpression Id. */
  int AND_ = 58;
  /** RegularExpression Id. */
  int ANY_ = 59;
  /** RegularExpression Id. */
  int ASC_ = 60;
  /** RegularExpression Id. */
  int AVERAGE_ = 61;
  /** RegularExpression Id. */
  int BIT_ = 62;
  /** RegularExpression Id. */
  int CSV_ = 63;
  /** RegularExpression Id. */
  int DAY_ = 64;
  /** RegularExpression Id. */
  int DBA_ = 65;
  /** RegularExpression Id. */
  int DEC_ = 66;
  /** RegularExpression Id. */
  int END_ = 67;
  /** RegularExpression Id. */
  int FOR_ = 68;
  /** RegularExpression Id. */
  int INT_ = 69;
  /** RegularExpression Id. */
  int MAX_ = 70;
  /** RegularExpression Id. */
  int MIN_ = 71;
  /** RegularExpression Id. */
  int NOT_ = 72;
  /** RegularExpression Id. */
  int RAW_ = 73;
  /** RegularExpression Id. */
  int SET_ = 74;
  /** RegularExpression Id. */
  int SUM_ = 75;
  /** RegularExpression Id. */
  int BLOB_ = 76;
  /** RegularExpression Id. */
  int BOTH = 77;
  /** RegularExpression Id. */
  int BYTE_ = 78;
  /** RegularExpression Id. */
  int CASE_ = 79;
  /** RegularExpression Id. */
  int CAST_ = 80;
  /** RegularExpression Id. */
  int CHAR_ = 81;
  /** RegularExpression Id. */
  int CIDR_ = 82;
  /** RegularExpression Id. */
  int CLOB_ = 83;
  /** RegularExpression Id. */
  int COPY_ = 84;
  /** RegularExpression Id. */
  int CORR_ = 85;
  /** RegularExpression Id. */
  int DATE_ = 86;
  /** RegularExpression Id. */
  int DESC_ = 87;
  /** RegularExpression Id. */
  int DROP_ = 88;
  /** RegularExpression Id. */
  int ELSE_ = 89;
  /** RegularExpression Id. */
  int FROM_ = 90;
  /** RegularExpression Id. */
  int FULL_ = 91;
  /** RegularExpression Id. */
  int HOUR_ = 92;
  /** RegularExpression Id. */
  int INET_ = 93;
  /** RegularExpression Id. */
  int INT2_ = 94;
  /** RegularExpression Id. */
  int INT4_ = 95;
  /** RegularExpression Id. */
  int INT8_ = 96;
  /** RegularExpression Id. */
  int INTO_ = 97;
  /** RegularExpression Id. */
  int JOIN_ = 98;
  /** RegularExpression Id. */
  int KILL_ = 99;
  /** RegularExpression Id. */
  int LEFT_ = 100;
  /** RegularExpression Id. */
  int LIKE_ = 101;
  /** RegularExpression Id. */
  int LONG_ = 102;
  /** RegularExpression Id. */
  int NODE_ = 103;
  /** RegularExpression Id. */
  int NULL_ = 104;
  /** RegularExpression Id. */
  int OIDS_ = 105;
  /** RegularExpression Id. */
  int PORT_ = 106;
  /** RegularExpression Id. */
  int REAL_ = 107;
  /** RegularExpression Id. */
  int SHOW_ = 108;
  /** RegularExpression Id. */
  int SOME_ = 109;
  /** RegularExpression Id. */
  int TEMP_ = 110;
  /** RegularExpression Id. */
  int TEXT_ = 111;
  /** RegularExpression Id. */
  int THEN_ = 112;
  /** RegularExpression Id. */
  int TIME_ = 113;
  /** RegularExpression Id. */
  int TRAN_ = 114;
  /** RegularExpression Id. */
  int TRIM_ = 115;
  /** RegularExpression Id. */
  int TRUE_ = 116;
  /** RegularExpression Id. */
  int TYPE_ = 117;
  /** RegularExpression Id. */
  int USER_ = 118;
  /** RegularExpression Id. */
  int VIEW_ = 119;
  /** RegularExpression Id. */
  int WEEK_ = 120;
  /** RegularExpression Id. */
  int WHEN_ = 121;
  /** RegularExpression Id. */
  int WITH_ = 122;
  /** RegularExpression Id. */
  int WORK_ = 123;
  /** RegularExpression Id. */
  int YEAR_ = 124;
  /** RegularExpression Id. */
  int AFTER_ = 125;
  /** RegularExpression Id. */
  int ALTER_ = 126;
  /** RegularExpression Id. */
  int BEGIN_ = 127;
  /** RegularExpression Id. */
  int BOX2D_ = 128;
  /** RegularExpression Id. */
  int BOX3D_ = 129;
  /** RegularExpression Id. */
  int BYTEA_ = 130;
  /** RegularExpression Id. */
  int CHECK_ = 131;
  /** RegularExpression Id. */
  int CLOSE_ = 132;
  /** RegularExpression Id. */
  int COUNT_ = 133;
  /** RegularExpression Id. */
  int CROSS_ = 134;
  /** RegularExpression Id. */
  int EVERY_ = 135;
  /** RegularExpression Id. */
  int FALSE_ = 136;
  /** RegularExpression Id. */
  int FETCH_ = 137;
  /** RegularExpression Id. */
  int FIRST_ = 138;
  /** RegularExpression Id. */
  int FIXED_ = 139;
  /** RegularExpression Id. */
  int FLOAT_ = 140;
  /** RegularExpression Id. */
  int FORCE_ = 141;
  /** RegularExpression Id. */
  int GRANT_ = 142;
  /** RegularExpression Id. */
  int ILIKE_ = 143;
  /** RegularExpression Id. */
  int IMAGE_ = 144;
  /** RegularExpression Id. */
  int INDEX_ = 145;
  /** RegularExpression Id. */
  int INNER_ = 146;
  /** RegularExpression Id. */
  int LIMIT_ = 147;
  /** RegularExpression Id. */
  int LOCAL_ = 148;
  /** RegularExpression Id. */
  int MONEY_ = 149;
  /** RegularExpression Id. */
  int MONTH_ = 150;
  /** RegularExpression Id. */
  int NCHAR_ = 151;
  /** RegularExpression Id. */
  int NODES_ = 152;
  /** RegularExpression Id. */
  int OUTER_ = 153;
  /** RegularExpression Id. */
  int OWNER_ = 154;
  /** RegularExpression Id. */
  int QUOTE_STRING_ = 155;
  /** RegularExpression Id. */
  int RIGHT_ = 156;
  /** RegularExpression Id. */
  int STDIN_ = 157;
  /** RegularExpression Id. */
  int TABLE_ = 158;
  /** RegularExpression Id. */
  int TEMPDOT_ = 159;
  /** RegularExpression Id. */
  int UNION_ = 160;
  /** RegularExpression Id. */
  int USING_ = 161;
  /** RegularExpression Id. */
  int WHERE_ = 162;
  /** RegularExpression Id. */
  int BIGINT_ = 163;
  /** RegularExpression Id. */
  int BINARY_ = 164;
  /** RegularExpression Id. */
  int BIT_OR_ = 165;
  /** RegularExpression Id. */
  int COLUMN_ = 166;
  /** RegularExpression Id. */
  int COMMIT_ = 167;
  /** RegularExpression Id. */
  int CREATE_ = 168;
  /** RegularExpression Id. */
  int CURSOR_ = 169;
  /** RegularExpression Id. */
  int DELETE_ = 170;
  /** RegularExpression Id. */
  int DIRECT_ = 171;
  /** RegularExpression Id. */
  int ESCAPE_ = 172;
  /** RegularExpression Id. */
  int EXISTS_ = 173;
  /** RegularExpression Id. */
  int FLOAT4_ = 174;
  /** RegularExpression Id. */
  int FLOAT8_ = 175;
  /** RegularExpression Id. */
  int FREEZE_ = 176;
  /** RegularExpression Id. */
  int GLOBAL_ = 177;
  /** RegularExpression Id. */
  int HAVING_ = 178;
  /** RegularExpression Id. */
  int INSERT_ = 179;
  /** RegularExpression Id. */
  int MANUAL_ = 180;
  /** RegularExpression Id. */
  int MINUTE_ = 181;
  /** RegularExpression Id. */
  int MODIFY_ = 182;
  /** RegularExpression Id. */
  int NULLIF_ = 183;
  /** RegularExpression Id. */
  int NUMBER_ = 184;
  /** RegularExpression Id. */
  int OFFSET_ = 185;
  /** RegularExpression Id. */
  int PARENT_ = 186;
  /** RegularExpression Id. */
  int PUBLIC_ = 187;
  /** RegularExpression Id. */
  int RENAME_ = 188;
  /** RegularExpression Id. */
  int REVOKE_ = 189;
  /** RegularExpression Id. */
  int SECOND_ = 190;
  /** RegularExpression Id. */
  int SELECT_ = 191;
  /** RegularExpression Id. */
  int SERIAL_ = 192;
  /** RegularExpression Id. */
  int STDDEV_ = 193;
  /** RegularExpression Id. */
  int STDOUT_ = 194;
  /** RegularExpression Id. */
  int UNIQUE_ = 195;
  /** RegularExpression Id. */
  int UPDATE_ = 196;
  /** RegularExpression Id. */
  int VACUUM_ = 197;
  /** RegularExpression Id. */
  int VARBIT_ = 198;
  /** RegularExpression Id. */
  int ANALYZE_ = 199;
  /** RegularExpression Id. */
  int BETWEEN_ = 200;
  /** RegularExpression Id. */
  int BIT_AND_ = 201;
  /** RegularExpression Id. */
  int BOOL_OR_ = 202;
  /** RegularExpression Id. */
  int CLUSTER_ = 203;
  /** RegularExpression Id. */
  int CONVERT_ = 204;
  /** RegularExpression Id. */
  int DECIMAL_ = 205;
  /** RegularExpression Id. */
  int DECLARE_ = 206;
  /** RegularExpression Id. */
  int DEFAULT_ = 207;
  /** RegularExpression Id. */
  int EXPLAIN_ = 208;
  /** RegularExpression Id. */
  int EXTRACT_ = 209;
  /** RegularExpression Id. */
  int INHERIT_ = 210;
  /** RegularExpression Id. */
  int INTEGER_ = 211;
  /** RegularExpression Id. */
  int LEADING = 212;
  /** RegularExpression Id. */
  int MACADDR_ = 213;
  /** RegularExpression Id. */
  int NATURAL_ = 214;
  /** RegularExpression Id. */
  int NUMERIC_ = 215;
  /** RegularExpression Id. */
  int OVERLAY_ = 216;
  /** RegularExpression Id. */
  int PLACING_ = 217;
  /** RegularExpression Id. */
  int PREPARE_ = 218;
  /** RegularExpression Id. */
  int PUBLICDOT_ = 219;
  /** RegularExpression Id. */
  int QUARTER_ = 220;
  /** RegularExpression Id. */
  int REGR_R2_ = 221;
  /** RegularExpression Id. */
  int REPLACE_ = 222;
  /** RegularExpression Id. */
  int SPATIAL_ = 223;
  /** RegularExpression Id. */
  int STORAGE_ = 224;
  /** RegularExpression Id. */
  int TINYINT_ = 225;
  /** RegularExpression Id. */
  int VARCHAR_ = 226;
  /** RegularExpression Id. */
  int VAR_POP_ = 227;
  /** RegularExpression Id. */
  int VARYING_ = 228;
  /** RegularExpression Id. */
  int VERBOSE_ = 229;
  /** RegularExpression Id. */
  int VERSION_ = 230;
  /** RegularExpression Id. */
  int ADD_NODE_ = 231;
  /** RegularExpression Id. */
  int ASBINARY_ = 232;
  /** RegularExpression Id. */
  int BOOL_AND_ = 233;
  /** RegularExpression Id. */
  int COALESCE_ = 234;
  /** RegularExpression Id. */
  int DATABASE_ = 235;
  /** RegularExpression Id. */
  int DATETIME_ = 236;
  /** RegularExpression Id. */
  int DESCRIBE_ = 237;
  /** RegularExpression Id. */
  int DISTINCT_ = 238;
  /** RegularExpression Id. */
  int GEOMETRY_ = 239;
  /** RegularExpression Id. */
  int INHERITS_ = 240;
  /** RegularExpression Id. */
  int INTERVAL_ = 241;
  /** RegularExpression Id. */
  int LOCATION_ = 242;
  /** RegularExpression Id. */
  int LONG_RAW_ = 243;
  /** RegularExpression Id. */
  int LONGTEXT_ = 244;
  /** RegularExpression Id. */
  int LVARCHAR_ = 245;
  /** RegularExpression Id. */
  int NATIONAL_ = 246;
  /** RegularExpression Id. */
  int OVERLAPS_ = 247;
  /** RegularExpression Id. */
  int PASSWORD_ = 248;
  /** RegularExpression Id. */
  int REGCLASS_ = 249;
  /** RegularExpression Id. */
  int REGR_SXX_ = 250;
  /** RegularExpression Id. */
  int REGR_SXY_ = 251;
  /** RegularExpression Id. */
  int REGR_SYY_ = 252;
  /** RegularExpression Id. */
  int RESOURCE_ = 253;
  /** RegularExpression Id. */
  int ROLLBACK_ = 254;
  /** RegularExpression Id. */
  int SHUT_DOWN_ = 255;
  /** RegularExpression Id. */
  int SMALLINT_ = 256;
  /** RegularExpression Id. */
  int STANDARD_ = 257;
  /** RegularExpression Id. */
  int TINYTEXT_ = 258;
  /** RegularExpression Id. */
  int TRAILING = 259;
  /** RegularExpression Id. */
  int TRUNCATE_ = 260;
  /** RegularExpression Id. */
  int UNLISTEN_ = 261;
  /** RegularExpression Id. */
  int UNSIGNED_ = 262;
  /** RegularExpression Id. */
  int VARCHAR2_ = 263;
  /** RegularExpression Id. */
  int VARIANCE_ = 264;
  /** RegularExpression Id. */
  int VAR_SAMP_ = 265;
  /** RegularExpression Id. */
  int ZEROFILL_ = 266;
  /** RegularExpression Id. */
  int BIGSERIAL_ = 267;
  /** RegularExpression Id. */
  int CHARACHTER_ = 268;
  /** RegularExpression Id. */
  int COVAR_POP_ = 269;
  /** RegularExpression Id. */
  int DELIMITER_ = 270;
  /** RegularExpression Id. */
  int DROP_NODE_ = 271;
  /** RegularExpression Id. */
  int QPUBLICDOT_ = 272;
  /** RegularExpression Id. */
  int READ_ONLY_ = 273;
  /** RegularExpression Id. */
  int REGR_AVGX_ = 274;
  /** RegularExpression Id. */
  int REGR_AVGY_ = 275;
  /** RegularExpression Id. */
  int SUBSTRING_ = 276;
  /** RegularExpression Id. */
  int TEMPORARY_ = 277;
  /** RegularExpression Id. */
  int TIMESTAMP_ = 278;
  /** RegularExpression Id. */
  int VARBINARY_ = 279;
  /** RegularExpression Id. */
  int BIGINTEGER_ = 280;
  /** RegularExpression Id. */
  int BITVARYING_ = 281;
  /** RegularExpression Id. */
  int CONSTRAINT_ = 282;
  /** RegularExpression Id. */
  int COVAR_SAMP_ = 283;
  /** RegularExpression Id. */
  int DEALLOCATE_ = 284;
  /** RegularExpression Id. */
  int MEDIUMTEXT_ = 285;
  /** RegularExpression Id. */
  int READ_WRITE_ = 286;
  /** RegularExpression Id. */
  int REFERENCES_ = 287;
  /** RegularExpression Id. */
  int REGR_COUNT_ = 288;
  /** RegularExpression Id. */
  int REGR_SLOPE_ = 289;
  /** RegularExpression Id. */
  int REPLICATED_ = 290;
  /** RegularExpression Id. */
  int SMALLFLOAT_ = 291;
  /** RegularExpression Id. */
  int SMALLMONEY_ = 292;
  /** RegularExpression Id. */
  int STATISTICS_ = 293;
  /** RegularExpression Id. */
  int STDDEV_POP_ = 294;
  /** RegularExpression Id. */
  int TABLESPACE_ = 295;
  /** RegularExpression Id. */
  int BOX3DEXTENT_ = 296;
  /** RegularExpression Id. */
  int PERIMETER2D_ = 297;
  /** RegularExpression Id. */
  int PERIMETER3D_ = 298;
  /** RegularExpression Id. */
  int STDDEV_SAMP_ = 299;
  /** RegularExpression Id. */
  int TRANSACTION_ = 300;
  /** RegularExpression Id. */
  int CURRENTDATE_ = 301;
  /** RegularExpression Id. */
  int CURRENT_TIME_ = 302;
  /** RegularExpression Id. */
  int CURRENT_USER_ = 303;
  /** RegularExpression Id. */
  int LONG_VARCHAR_ = 304;
  /** RegularExpression Id. */
  int SERIALIZABLE_ = 305;
  /** RegularExpression Id. */
  int VARIANCE_POP_ = 306;
  /** RegularExpression Id. */
  int SAMLLDATETIME_ = 307;
  /** RegularExpression Id. */
  int VARIANCE_SAMP_ = 308;
  /** RegularExpression Id. */
  int CURRENT_SCHEMA_ = 309;
  /** RegularExpression Id. */
  int REGR_INTERCEPT_ = 310;
  /** RegularExpression Id. */
  int CLOCK_TIMESTAMP_ = 311;
  /** RegularExpression Id. */
  int CURRENT_DATABASE_ = 312;
  /** RegularExpression Id. */
  int ADDGEOMETRYCOLUMN_ = 313;
  /** RegularExpression Id. */
  int CURRENT_TIMESTAMP_ = 314;
  /** RegularExpression Id. */
  int STATEMENT_TIMESTAMP_ = 315;
  /** RegularExpression Id. */
  int TRANSACTION_TIMESTAMP_ = 316;
  /** RegularExpression Id. */
  int ONLY_ = 317;
  /** RegularExpression Id. */
  int UNARY_SIGN_ = 318;
  /** RegularExpression Id. */
  int ORDER_BY_ = 319;
  /** RegularExpression Id. */
  int UPDATE_STAT_ = 320;
  /** RegularExpression Id. */
  int PRIMARYKEY_ = 321;
  /** RegularExpression Id. */
  int FOREIGNKEY_ = 322;
  /** RegularExpression Id. */
  int PARTITIONINGKEY_ = 323;
  /** RegularExpression Id. */
  int ROUND_ROBIN_ = 324;
  /** RegularExpression Id. */
  int WITH_XROWID_ = 325;
  /** RegularExpression Id. */
  int WITHOUT_XROWID_ = 326;
  /** RegularExpression Id. */
  int PARTITION_WITH_ = 327;
  /** RegularExpression Id. */
  int START_DB_ = 328;
  /** RegularExpression Id. */
  int WAIT_TIMEOUT_ = 329;
  /** RegularExpression Id. */
  int STOP_DB_ = 330;
  /** RegularExpression Id. */
  int CREATE_DB_ = 331;
  /** RegularExpression Id. */
  int CREATE_NODE_ = 332;
  /** RegularExpression Id. */
  int DROP_DB_ = 333;
  /** RegularExpression Id. */
  int SHOW_AGENTS_ = 334;
  /** RegularExpression Id. */
  int SHOW_CLUSTER_ = 335;
  /** RegularExpression Id. */
  int SHOW_STATEMENTS_ = 336;
  /** RegularExpression Id. */
  int SHOW_DATABASES_ = 337;
  /** RegularExpression Id. */
  int SHOW_TABLES_ = 338;
  /** RegularExpression Id. */
  int SHOW_TRAN_ISOLATION_ = 339;
  /** RegularExpression Id. */
  int REPEATABLE_READ_ = 340;
  /** RegularExpression Id. */
  int READ_COMMITTED_ = 341;
  /** RegularExpression Id. */
  int READ_UNCOMMITTED_ = 342;
  /** RegularExpression Id. */
  int ISOLATION_LEVEL_ = 343;
  /** RegularExpression Id. */
  int SHOW_CONSTRAINTS_ = 344;
  /** RegularExpression Id. */
  int OWNER_TO_ = 345;
  /** RegularExpression Id. */
  int SHOW_TABLE_ = 346;
  /** RegularExpression Id. */
  int SHOW_VIEW_ = 347;
  /** RegularExpression Id. */
  int SHOW_VIEWS_ = 348;
  /** RegularExpression Id. */
  int SHOW_USERS_ = 349;
  /** RegularExpression Id. */
  int FORCE_NOT_NULL_ = 350;
  /** RegularExpression Id. */
  int FORCE_QUOTE_ = 351;
  /** RegularExpression Id. */
  int ON_COMMIT_ = 352;
  /** RegularExpression Id. */
  int PRESERVE_ROWS_ = 353;
  /** RegularExpression Id. */
  int DELETE_ROWS_ = 354;
  /** RegularExpression Id. */
  int GROUP_BY_ = 355;
  /** RegularExpression Id. */
  int EXEC_ = 356;
  /** RegularExpression Id. */
  int SIMILAR_TO_ = 357;
  /** RegularExpression Id. */
  int SHOW_INDEXES_ = 358;
  /** RegularExpression Id. */
  int WITH_TIMEZONE_ = 359;
  /** RegularExpression Id. */
  int WITHOUT_TIMEZONE_ = 360;
  /** RegularExpression Id. */
  int DOUBLE_PRECISION_ = 361;
  /** RegularExpression Id. */
  int BOOLEAN_ = 362;
  /** RegularExpression Id. */
  int YEAR_FROM = 363;
  /** RegularExpression Id. */
  int QUARTER_FROM = 364;
  /** RegularExpression Id. */
  int MONTH_FROM = 365;
  /** RegularExpression Id. */
  int WEEK_FROM = 366;
  /** RegularExpression Id. */
  int DAY_FROM = 367;
  /** RegularExpression Id. */
  int DOY_FROM = 368;
  /** RegularExpression Id. */
  int DOW_FROM = 369;
  /** RegularExpression Id. */
  int DECADE_FROM = 370;
  /** RegularExpression Id. */
  int CENTURY_FROM = 371;
  /** RegularExpression Id. */
  int HOUR_FROM = 372;
  /** RegularExpression Id. */
  int MINUTE_FROM = 373;
  /** RegularExpression Id. */
  int SECOND_FROM = 374;
  /** RegularExpression Id. */
  int MILLISECOND_FROM = 375;
  /** RegularExpression Id. */
  int MILLENNIUM_FROM = 376;
  /** RegularExpression Id. */
  int MICROSECONDS_FROM = 377;
  /** RegularExpression Id. */
  int EPOCH_FROM = 378;
  /** RegularExpression Id. */
  int POSITION_ = 379;
  /** RegularExpression Id. */
  int VALUES_ = 380;
  /** RegularExpression Id. */
  int SINGLEDIGIT = 381;
  /** RegularExpression Id. */
  int INT_LITERAL = 382;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 383;
  /** RegularExpression Id. */
  int SCIENTIFIC_LITERAL = 384;
  /** RegularExpression Id. */
  int STRING_LITERAL = 385;
  /** RegularExpression Id. */
  int PARAM_PLACE_HOLDER = 386;
  /** RegularExpression Id. */
  int INTERVAL_LITERAL = 387;
  /** RegularExpression Id. */
  int DATE_LITERAL = 388;
  /** RegularExpression Id. */
  int TIME_LITERAL = 389;
  /** RegularExpression Id. */
  int TIMESTAMP_LITERAL = 390;
  /** RegularExpression Id. */
  int TEXT_LITERAL = 391;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 392;
  /** RegularExpression Id. */
  int MACADDR_LITERAL = 393;
  /** RegularExpression Id. */
  int CIDR_LITERAL = 394;
  /** RegularExpression Id. */
  int INET_LITERAL = 395;
  /** RegularExpression Id. */
  int GEOMETRY_LITERAL = 396;
  /** RegularExpression Id. */
  int BINARY_LITERAL = 397;
  /** RegularExpression Id. */
  int HEXDECIMAL_LITERAL = 398;
  /** RegularExpression Id. */
  int LETTER = 399;
  /** RegularExpression Id. */
  int IDENTIFIER = 400;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 401;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<COMMENT_LINE>",
    "<COMMENT_BLOCK>",
    "\"~\"",
    "\"<\"",
    "\"=\"",
    "\">\"",
    "\"|\"",
    "\"-\"",
    "\";\"",
    "\"!\"",
    "\"/\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\"@\"",
    "\"*\"",
    "\"&\"",
    "\"#\"",
    "\"%\"",
    "\"+\"",
    "\"~=\"",
    "\"~*\"",
    "\"<<\"",
    "\"<=\"",
    "\"<>\"",
    "\">=\"",
    "\">>\"",
    "\"||\"",
    "\"|/\"",
    "\"!~\"",
    "\"!=\"",
    "\"!!\"",
    "\"&<\"",
    "\"&>\"",
    "\"&&\"",
    "\"AS\"",
    "\"IN\"",
    "\"IS\"",
    "\"NO\"",
    "\"ON\"",
    "\"OR\"",
    "\"TO\"",
    "\"<<=\"",
    "\"<<|\"",
    "\">>=\"",
    "\"|>>\"",
    "\"||/\"",
    "\"|&>\"",
    "\"!~*\"",
    "\"(+)\"",
    "\"&<|\"",
    "\"ADD\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"ASC\"",
    "\"AVG\"",
    "\"BIT\"",
    "\"CSV\"",
    "\"DAY\"",
    "\"DBA\"",
    "\"DEC\"",
    "\"END\"",
    "\"FOR\"",
    "\"INT\"",
    "\"MAX\"",
    "\"MIN\"",
    "\"NOT\"",
    "\"RAW\"",
    "\"SET\"",
    "\"SUM\"",
    "\"BLOB\"",
    "\"BOTH\"",
    "\"BYTE\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CHAR\"",
    "\"CIDR\"",
    "\"CLOB\"",
    "\"COPY\"",
    "\"CORR\"",
    "\"DATE\"",
    "\"DESC\"",
    "\"DROP\"",
    "\"ELSE\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"HOUR\"",
    "\"INET\"",
    "\"INT2\"",
    "\"INT4\"",
    "\"INT8\"",
    "\"INTO\"",
    "\"JOIN\"",
    "\"KILL\"",
    "\"LEFT\"",
    "\"LIKE\"",
    "\"LONG\"",
    "\"NODE\"",
    "\"NULL\"",
    "\"OIDS\"",
    "\"PORT\"",
    "\"REAL\"",
    "\"SHOW\"",
    "\"SOME\"",
    "\"TEMP\"",
    "\"TEXT\"",
    "\"THEN\"",
    "\"TIME\"",
    "\"TRAN\"",
    "\"TRIM\"",
    "\"TRUE\"",
    "\"TYPE\"",
    "\"USER\"",
    "\"VIEW\"",
    "\"WEEK\"",
    "\"WHEN\"",
    "\"WITH\"",
    "\"WORK\"",
    "\"YEAR\"",
    "\"AFTER\"",
    "\"ALTER\"",
    "\"BEGIN\"",
    "\"BOX2D\"",
    "\"BOX3D\"",
    "\"BYTEA\"",
    "\"CHECK\"",
    "\"CLOSE\"",
    "\"COUNT\"",
    "\"CROSS\"",
    "\"EVERY\"",
    "\"FALSE\"",
    "\"FETCH\"",
    "\"FIRST\"",
    "\"FIXED\"",
    "\"FLOAT\"",
    "\"FORCE\"",
    "\"GRANT\"",
    "\"ILIKE\"",
    "\"IMAGE\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"LIMIT\"",
    "\"LOCAL\"",
    "\"MONEY\"",
    "\"MONTH\"",
    "\"NCHAR\"",
    "\"NODES\"",
    "\"OUTER\"",
    "\"OWNER\"",
    "\"QUOTE\"",
    "\"RIGHT\"",
    "\"STDIN\"",
    "\"TABLE\"",
    "\"TEMP.\"",
    "\"UNION\"",
    "\"USING\"",
    "\"WHERE\"",
    "\"BIGINT\"",
    "\"BINARY\"",
    "\"BIT_OR\"",
    "\"COLUMN\"",
    "\"COMMIT\"",
    "\"CREATE\"",
    "\"CURSOR\"",
    "\"DELETE\"",
    "\"DIRECT\"",
    "\"ESCAPE\"",
    "\"EXISTS\"",
    "\"FLOAT4\"",
    "\"FLOAT8\"",
    "\"FREEZE\"",
    "\"GLOBAL\"",
    "\"HAVING\"",
    "\"INSERT\"",
    "\"MANUAL\"",
    "\"MINUTE\"",
    "\"MODIFY\"",
    "\"NULLIF\"",
    "\"NUMBER\"",
    "\"OFFSET\"",
    "\"PARENT\"",
    "\"PUBLIC\"",
    "\"RENAME\"",
    "\"REVOKE\"",
    "\"SECOND\"",
    "\"SELECT\"",
    "\"SERIAL\"",
    "\"STDDEV\"",
    "\"STDOUT\"",
    "\"UNIQUE\"",
    "\"UPDATE\"",
    "\"VACUUM\"",
    "\"VARBIT\"",
    "\"ANALYZE\"",
    "\"BETWEEN\"",
    "\"BIT_AND\"",
    "\"BOOL_OR\"",
    "\"CLUSTER\"",
    "\"CONVERT\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"EXPLAIN\"",
    "\"EXTRACT\"",
    "\"INHERIT\"",
    "\"INTEGER\"",
    "\"LEADING\"",
    "\"MACADDR\"",
    "\"NATURAL\"",
    "\"NUMERIC\"",
    "\"OVERLAY\"",
    "\"PLACING\"",
    "\"PREPARE\"",
    "\"PUBLIC.\"",
    "\"QUARTER\"",
    "\"REGR_R2\"",
    "\"REPLACE\"",
    "\"SPATIAL\"",
    "\"STORAGE\"",
    "\"TINYINT\"",
    "\"VARCHAR\"",
    "\"VAR_POP\"",
    "\"VARYING\"",
    "\"VERBOSE\"",
    "\"VERSION\"",
    "\"ADD NODE\"",
    "\"ASBINARY\"",
    "\"BOOL_AND\"",
    "\"COALESCE\"",
    "\"DATABASE\"",
    "\"DATETIME\"",
    "\"DESCRIBE\"",
    "\"DISTINCT\"",
    "\"GEOMETRY\"",
    "\"INHERITS\"",
    "\"INTERVAL\"",
    "\"LOCATION\"",
    "\"LONG RAW\"",
    "\"LONGTEXT\"",
    "\"LVARCHAR\"",
    "\"NATIONAL\"",
    "\"OVERLAPS\"",
    "\"PASSWORD\"",
    "\"REGCLASS\"",
    "\"REGR_SXX\"",
    "\"REGR_SXY\"",
    "\"REGR_SYY\"",
    "\"RESOURCE\"",
    "\"ROLLBACK\"",
    "\"SHUTDOWN\"",
    "\"SMALLINT\"",
    "\"STANDARD\"",
    "\"TINYTEXT\"",
    "\"TRAILING\"",
    "\"TRUNCATE\"",
    "\"UNLISTEN\"",
    "\"UNSIGNED\"",
    "\"VARCHAR2\"",
    "\"VARIANCE\"",
    "\"VAR_SAMP\"",
    "\"ZEROFILL\"",
    "\"BIGSERIAL\"",
    "\"CHARACTER\"",
    "\"COVAR_POP\"",
    "\"DELIMITER\"",
    "\"DROP NODE\"",
    "\"\\\"PUBLIC\\\".\"",
    "\"READ_ONLY\"",
    "\"REGR_AVGX\"",
    "\"REGR_AVGY\"",
    "\"SUBSTRING\"",
    "\"TEMPORARY\"",
    "\"TIMESTAMP\"",
    "\"VARBINARY\"",
    "\"BIGINTEGER\"",
    "\"BITVARYING\"",
    "\"CONSTRAINT\"",
    "\"COVAR_SAMP\"",
    "\"DEALLOCATE\"",
    "\"MEDIUMTEXT\"",
    "\"READ_WRITE\"",
    "\"REFERENCES\"",
    "\"REGR_COUNT\"",
    "\"REGR_SLOPE\"",
    "\"REPLICATED\"",
    "\"SMALLFLOAT\"",
    "\"SMALLMONEY\"",
    "\"STATISTICS\"",
    "\"STDDEV_POP\"",
    "\"TABLESPACE\"",
    "\"BOX3DEXTENT\"",
    "\"PERIMETER2D\"",
    "\"PERIMETER3D\"",
    "\"STDDEV_SAMP\"",
    "\"TRANSACTION\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_TIME\"",
    "\"CURRENT_USER\"",
    "\"LONG VARCHAR\"",
    "\"SERIALIZABLE\"",
    "\"VARIANCE_POP\"",
    "\"SMALLDATETIME\"",
    "\"VARIANCE_SAMP\"",
    "\"CURRENT_SCHEMA\"",
    "\"REGR_INTERCEPT\"",
    "\"CLOCK_TIMESTAMP\"",
    "\"CURRENT_DATABASE\"",
    "\"ADDGEOMETRYCOLUMN\"",
    "\"CURRENT_TIMESTAMP\"",
    "\"STATEMENT_TIMESTAMP\"",
    "\"TRANSACTION_TIMESTAMP\"",
    "\"ONLY\"",
    "<UNARY_SIGN_>",
    "<ORDER_BY_>",
    "<UPDATE_STAT_>",
    "<PRIMARYKEY_>",
    "<FOREIGNKEY_>",
    "<PARTITIONINGKEY_>",
    "<ROUND_ROBIN_>",
    "<WITH_XROWID_>",
    "<WITHOUT_XROWID_>",
    "<PARTITION_WITH_>",
    "<START_DB_>",
    "<WAIT_TIMEOUT_>",
    "<STOP_DB_>",
    "<CREATE_DB_>",
    "<CREATE_NODE_>",
    "<DROP_DB_>",
    "<SHOW_AGENTS_>",
    "<SHOW_CLUSTER_>",
    "<SHOW_STATEMENTS_>",
    "<SHOW_DATABASES_>",
    "<SHOW_TABLES_>",
    "<SHOW_TRAN_ISOLATION_>",
    "<REPEATABLE_READ_>",
    "<READ_COMMITTED_>",
    "<READ_UNCOMMITTED_>",
    "<ISOLATION_LEVEL_>",
    "<SHOW_CONSTRAINTS_>",
    "<OWNER_TO_>",
    "<SHOW_TABLE_>",
    "<SHOW_VIEW_>",
    "<SHOW_VIEWS_>",
    "<SHOW_USERS_>",
    "<FORCE_NOT_NULL_>",
    "<FORCE_QUOTE_>",
    "<ON_COMMIT_>",
    "<PRESERVE_ROWS_>",
    "<DELETE_ROWS_>",
    "<GROUP_BY_>",
    "<EXEC_>",
    "<SIMILAR_TO_>",
    "<SHOW_INDEXES_>",
    "<WITH_TIMEZONE_>",
    "<WITHOUT_TIMEZONE_>",
    "<DOUBLE_PRECISION_>",
    "<BOOLEAN_>",
    "<YEAR_FROM>",
    "<QUARTER_FROM>",
    "<MONTH_FROM>",
    "<WEEK_FROM>",
    "<DAY_FROM>",
    "<DOY_FROM>",
    "<DOW_FROM>",
    "<DECADE_FROM>",
    "<CENTURY_FROM>",
    "<HOUR_FROM>",
    "<MINUTE_FROM>",
    "<SECOND_FROM>",
    "<MILLISECOND_FROM>",
    "<MILLENNIUM_FROM>",
    "<MICROSECONDS_FROM>",
    "<EPOCH_FROM>",
    "\"POSITION\"",
    "\"VALUES\"",
    "<SINGLEDIGIT>",
    "<INT_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<SCIENTIFIC_LITERAL>",
    "<STRING_LITERAL>",
    "<PARAM_PLACE_HOLDER>",
    "<INTERVAL_LITERAL>",
    "<DATE_LITERAL>",
    "<TIME_LITERAL>",
    "<TIMESTAMP_LITERAL>",
    "<TEXT_LITERAL>",
    "<INTEGER_LITERAL>",
    "<MACADDR_LITERAL>",
    "<CIDR_LITERAL>",
    "<INET_LITERAL>",
    "<GEOMETRY_LITERAL>",
    "<BINARY_LITERAL>",
    "<HEXDECIMAL_LITERAL>",
    "<LETTER>",
    "<IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "\",\"",
    "\".\"",
    "\"::\"",
  };

}
