/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class AlterDefOperationType implements INode {

  public NodeToken f0;

  public types f1;

  public NodeOptional f2;

  private static final long serialVersionUID = 144L;

  public AlterDefOperationType(final NodeToken n0, final types n1, final NodeOptional n2) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
  }

  public AlterDefOperationType(final types n0, final NodeOptional n1) {
    f0 = new NodeToken("TYPE");
    f1 = n0;
    f2 = n1;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
