/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class AlterTableSpace implements INode {

  public NodeToken f0;

  public Identifier f1;

  public NodeToken f2;

  public NodeToken f3;

  public Identifier f4;

  private static final long serialVersionUID = 144L;

  public AlterTableSpace(final NodeToken n0, final Identifier n1, final NodeToken n2, final NodeToken n3, final Identifier n4) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
  }

  public AlterTableSpace(final Identifier n0, final Identifier n1) {
    f0 = new NodeToken("TABLESPACE");
    f1 = n0;
    f2 = new NodeToken("RENAME");
    f3 = new NodeToken("TO");
    f4 = n1;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
