/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class ColumnDeclare implements INode {

  public Identifier f0;

  public types f1;

  public NodeOptional f2;

  public NodeOptional f3;

  public NodeOptional f4;

  public NodeOptional f5;

  private static final long serialVersionUID = 144L;

  public ColumnDeclare(final Identifier n0, final types n1, final NodeOptional n2, final NodeOptional n3, final NodeOptional n4, final NodeOptional n5) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
