/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class CreateDatabase implements INode {

  public NodeToken f0;

  public Identifier f1;

  public NodeOptional f2;

  public NodeOptional f3;

  public NodeToken f4;

  public NodeChoice f5;

  public NodeToken f6;

  public NodeListOptional f7;

  private static final long serialVersionUID = 144L;

  public CreateDatabase(final NodeToken n0, final Identifier n1, final NodeOptional n2, final NodeOptional n3, final NodeToken n4, final NodeChoice n5, final NodeToken n6, final NodeListOptional n7) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
  }

  public CreateDatabase(final Identifier n0, final NodeOptional n1, final NodeOptional n2, final NodeChoice n3, final NodeToken n4, final NodeListOptional n5) {
    f0 = new NodeToken("DATABASE");
    f1 = n0;
    f2 = n1;
    f3 = n2;
    f4 = new NodeToken("ON");
    f5 = n3;
    f6 = n4;
    f7 = n5;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
