/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class createView implements INode {

  public NodeChoice f0;

  public NodeToken f1;

  public TableName f2;

  public NodeOptional f3;

  public NodeToken f4;

  public SelectWithoutOrder f5;

  private static final long serialVersionUID = 144L;

  public createView(final NodeChoice n0, final NodeToken n1, final TableName n2, final NodeOptional n3, final NodeToken n4, final SelectWithoutOrder n5) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
  }

  public createView(final NodeChoice n0, final TableName n1, final NodeOptional n2, final SelectWithoutOrder n3) {
    f0 = n0;
    f1 = new NodeToken("VIEW");
    f2 = n1;
    f3 = n2;
    f4 = new NodeToken("AS");
    f5 = n3;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
