/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class createIndex implements INode {

  public NodeToken f0;

  public NodeOptional f1;

  public NodeToken f2;

  public Identifier f3;

  public NodeToken f4;

  public TableName f5;

  public NodeOptional f6;

  public NodeToken f7;

  public columnListIndexSpec f8;

  public NodeToken f9;

  public NodeOptional f10;

  public NodeOptional f11;

  private static final long serialVersionUID = 144L;

  public createIndex(final NodeToken n0, final NodeOptional n1, final NodeToken n2, final Identifier n3, final NodeToken n4, final TableName n5, final NodeOptional n6, final NodeToken n7, final columnListIndexSpec n8, final NodeToken n9, final NodeOptional n10, final NodeOptional n11) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
    f8 = n8;
    f9 = n9;
    f10 = n10;
    f11 = n11;
  }

  public createIndex(final NodeOptional n0, final Identifier n1, final TableName n2, final NodeOptional n3, final columnListIndexSpec n4, final NodeOptional n5, final NodeOptional n6) {
    f0 = new NodeToken("CREATE");
    f1 = n0;
    f2 = new NodeToken("INDEX");
    f3 = n1;
    f4 = new NodeToken("ON");
    f5 = n2;
    f6 = n3;
    f7 = new NodeToken("(");
    f8 = n4;
    f9 = new NodeToken(")");
    f10 = n5;
    f11 = n6;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
