/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class createTable implements INode {

  public NodeToken f0;

  public NodeOptional f1;

  public NodeToken f2;

  public TableName f3;

  public NodeChoice f4;

  private static final long serialVersionUID = 144L;

  public createTable(final NodeToken n0, final NodeOptional n1, final NodeToken n2, final TableName n3, final NodeChoice n4) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
  }

  public createTable(final NodeOptional n0, final TableName n1, final NodeChoice n2) {
    f0 = new NodeToken("CREATE");
    f1 = n0;
    f2 = new NodeToken("TABLE");
    f3 = n1;
    f4 = n2;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
