/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class ForeignKeyDef implements INode {

  public NodeToken f0;

  public NodeToken f1;

  public ColumnNameList f2;

  public NodeToken f3;

  public NodeToken f4;

  public TableName f5;

  public NodeToken f6;

  public ColumnNameList f7;

  public NodeToken f8;

  private static final long serialVersionUID = 144L;

  public ForeignKeyDef(final NodeToken n0, final NodeToken n1, final ColumnNameList n2, final NodeToken n3, final NodeToken n4, final TableName n5, final NodeToken n6, final ColumnNameList n7, final NodeToken n8) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
    f8 = n8;
  }

  public ForeignKeyDef(final ColumnNameList n0, final TableName n1, final ColumnNameList n2) {
    f0 = new NodeToken("KEY");
    f1 = new NodeToken("(");
    f2 = n0;
    f3 = new NodeToken(")");
    f4 = new NodeToken("REFERENCES");
    f5 = n1;
    f6 = new NodeToken("(");
    f7 = n2;
    f8 = new NodeToken(")");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
