/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class Func_Trim implements INode {

  public NodeToken f0;

  public NodeToken f1;

  public NodeChoice f2;

  public NodeOptional f3;

  public NodeToken f4;

  public SQLArgument f5;

  public NodeToken f6;

  private static final long serialVersionUID = 144L;

  public Func_Trim(final NodeToken n0, final NodeToken n1, final NodeChoice n2, final NodeOptional n3, final NodeToken n4, final SQLArgument n5, final NodeToken n6) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
  }

  public Func_Trim(final NodeChoice n0, final NodeOptional n1, final SQLArgument n2) {
    f0 = new NodeToken("TRIM");
    f1 = new NodeToken("(");
    f2 = n0;
    f3 = n1;
    f4 = new NodeToken("FROM");
    f5 = n2;
    f6 = new NodeToken(")");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
