/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class Func_NullIf implements INode {

  public NodeToken f0;

  public NodeToken f1;

  public SQLArgument f2;

  public NodeToken f3;

  public SQLArgument f4;

  public NodeToken f5;

  private static final long serialVersionUID = 144L;

  public Func_NullIf(final NodeToken n0, final NodeToken n1, final SQLArgument n2, final NodeToken n3, final SQLArgument n4, final NodeToken n5) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
  }

  public Func_NullIf(final SQLArgument n0, final SQLArgument n1) {
    f0 = new NodeToken("NULLIF");
    f1 = new NodeToken("(");
    f2 = n0;
    f3 = new NodeToken(",");
    f4 = n1;
    f5 = new NodeToken(")");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
