/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class Func_Convert implements INode {

  public NodeToken f0;

  public NodeToken f1;

  public SQLArgument f2;

  public NodeChoice f3;

  public NodeChoice f4;

  public NodeOptional f5;

  public NodeToken f6;

  private static final long serialVersionUID = 144L;

  public Func_Convert(final NodeToken n0, final NodeToken n1, final SQLArgument n2, final NodeChoice n3, final NodeChoice n4, final NodeOptional n5, final NodeToken n6) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
  }

  public Func_Convert(final SQLArgument n0, final NodeChoice n1, final NodeChoice n2, final NodeOptional n3) {
    f0 = new NodeToken("CONVERT");
    f1 = new NodeToken("(");
    f2 = n0;
    f3 = n1;
    f4 = n2;
    f5 = n3;
    f6 = new NodeToken(")");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
