/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.IRetArguVisitor;
import org.postgresql.stado.parser.core.visitor.IRetVisitor;
import org.postgresql.stado.parser.core.visitor.IVoidArguVisitor;
import org.postgresql.stado.parser.core.visitor.IVoidVisitor;

public interface INode extends java.io.Serializable {

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu);

  public <R> R accept(final IRetVisitor<R> vis);

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu);

  public void accept(final IVoidVisitor vis);

}
