/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class IntoClause implements INode {

  public NodeToken f0;

  public NodeOptional f1;

  public NodeOptional f2;

  public TableName f3;

  private static final long serialVersionUID = 144L;

  public IntoClause(final NodeToken n0, final NodeOptional n1, final NodeOptional n2, final TableName n3) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
  }

  public IntoClause(final NodeOptional n0, final NodeOptional n1, final TableName n2) {
    f0 = new NodeToken("INTO");
    f1 = n0;
    f2 = n1;
    f3 = n2;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
