/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class PseudoColumn implements INode {

  public NodeToken f0;

  public NodeToken f1;

  public NodeOptional f2;

  public SelectList f3;

  public NodeOptional f4;

  public NodeOptional f5;

  public NodeOptional f6;

  public NodeOptional f7;

  public NodeToken f8;

  private static final long serialVersionUID = 144L;

  public PseudoColumn(final NodeToken n0, final NodeToken n1, final NodeOptional n2, final SelectList n3, final NodeOptional n4, final NodeOptional n5, final NodeOptional n6, final NodeOptional n7, final NodeToken n8) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
    f8 = n8;
  }

  public PseudoColumn(final NodeOptional n0, final SelectList n1, final NodeOptional n2, final NodeOptional n3, final NodeOptional n4, final NodeOptional n5) {
    f0 = new NodeToken("(");
    f1 = new NodeToken("SELECT");
    f2 = n0;
    f3 = n1;
    f4 = n2;
    f5 = n3;
    f6 = n4;
    f7 = n5;
    f8 = new NodeToken(")");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
