/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class Revoke implements INode {

  public NodeToken f0;

  public PrivilegeList f1;

  public NodeToken f2;

  public NodeOptional f3;

  public TableListForGrant f4;

  public NodeToken f5;

  public GranteeList f6;

  private static final long serialVersionUID = 144L;

  public Revoke(final NodeToken n0, final PrivilegeList n1, final NodeToken n2, final NodeOptional n3, final TableListForGrant n4, final NodeToken n5, final GranteeList n6) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
  }

  public Revoke(final PrivilegeList n0, final NodeOptional n1, final TableListForGrant n2, final GranteeList n3) {
    f0 = new NodeToken("REVOKE");
    f1 = n0;
    f2 = new NodeToken("ON");
    f3 = n1;
    f4 = n2;
    f5 = new NodeToken("FROM");
    f6 = n3;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
