/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class SelectAddGeometryColumn implements INode {

  public NodeToken f0;

  public NodeToken f1;

  public NodeToken f2;

  public SQLArgument f3;

  public NodeToken f4;

  public SQLArgument f5;

  public NodeToken f6;

  public SQLArgument f7;

  public NodeToken f8;

  public SQLArgument f9;

  public NodeToken f10;

  public SQLArgument f11;

  public NodeOptional f12;

  public NodeOptional f13;

  public NodeToken f14;

  private static final long serialVersionUID = 144L;

  public SelectAddGeometryColumn(final NodeToken n0, final NodeToken n1, final NodeToken n2, final SQLArgument n3, final NodeToken n4, final SQLArgument n5, final NodeToken n6, final SQLArgument n7, final NodeToken n8, final SQLArgument n9, final NodeToken n10, final SQLArgument n11, final NodeOptional n12, final NodeOptional n13, final NodeToken n14) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
    f8 = n8;
    f9 = n9;
    f10 = n10;
    f11 = n11;
    f12 = n12;
    f13 = n13;
    f14 = n14;
  }

  public SelectAddGeometryColumn(final SQLArgument n0, final SQLArgument n1, final SQLArgument n2, final SQLArgument n3, final SQLArgument n4, final NodeOptional n5, final NodeOptional n6) {
    f0 = new NodeToken("SELECT");
    f1 = new NodeToken("ADDGEOMETRYCOLUMN");
    f2 = new NodeToken("(");
    f3 = n0;
    f4 = new NodeToken(",");
    f5 = n1;
    f6 = new NodeToken(",");
    f7 = n2;
    f8 = new NodeToken(",");
    f9 = n3;
    f10 = new NodeToken(",");
    f11 = n4;
    f12 = n5;
    f13 = n6;
    f14 = new NodeToken(")");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
