/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class SQLInClause implements INode {

  public NodeOptional f0;

  public NodeToken f1;

  public NodeChoice f2;

  public NodeToken f3;

  private static final long serialVersionUID = 144L;

  public SQLInClause(final NodeOptional n0, final NodeToken n1, final NodeChoice n2, final NodeToken n3) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
  }

  public SQLInClause(final NodeOptional n0, final NodeChoice n1) {
    f0 = n0;
    f1 = new NodeToken("IN");
    f2 = n1;
    f3 = new NodeToken(")");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
