/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class UpdateTable implements INode {

  public NodeToken f0;

  public TableName f1;

  public NodeToken f2;

  public SetUpdateClause f3;

  public NodeListOptional f4;

  public NodeOptional f5;

  private static final long serialVersionUID = 144L;

  public UpdateTable(final NodeToken n0, final TableName n1, final NodeToken n2, final SetUpdateClause n3, final NodeListOptional n4, final NodeOptional n5) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
  }

  public UpdateTable(final TableName n0, final SetUpdateClause n1, final NodeListOptional n2, final NodeOptional n3) {
    f0 = new NodeToken("UPDATE");
    f1 = n0;
    f2 = new NodeToken("SET");
    f3 = n1;
    f4 = n2;
    f5 = n3;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
