/* Generated by JTB 1.4.4 */
package org.postgresql.stado.parser.core.syntaxtree;

import org.postgresql.stado.parser.core.visitor.*;

public class WithDef implements INode {

  public Identifier f0;

  public NodeOptional f1;

  public NodeToken f2;

  public NodeToken f3;

  public SelectWithoutOrder f4;

  public NodeToken f5;

  private static final long serialVersionUID = 144L;

  public WithDef(final Identifier n0, final NodeOptional n1, final NodeToken n2, final NodeToken n3, final SelectWithoutOrder n4, final NodeToken n5) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
  }

  public WithDef(final Identifier n0, final NodeOptional n1, final SelectWithoutOrder n2) {
    f0 = n0;
    f1 = n1;
    f2 = new NodeToken("AS");
    f3 = new NodeToken("(");
    f4 = n2;
    f5 = new NodeToken(")");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
